baseURL = "https://electricgerbil.art/"
languageCode = "en-US"
title = "Electric Gerbil Arts"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-550TQB4CNE"
enableRobotsTXT = true
disableFastRender = true

theme = "hugo-sustain"

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "/images/electric-gerbil-logo.webp"
  author = "Electric Gerbil Arts"
  description = "A simple homepage"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/electric-gerbil.css", "css/carousel.css"]
  custom_js  = ["js/carousel.js"]

  # flip this for localhost debugging
  httpsOnly  = false

[params.social]
  Instagram     = "electricgerbil"
  Github        = ""
  Email         = ""
  Twitter       = ""
  LinkedIn      = ""
  Stackoverflow = ""
  Medium        = ""
  Telegram      = ""
  RSS           = ""

# ## Main Menu
[[menu.main]]
  name = "art"
  identifier = "art"
  weight = 200
  url = "/art/"
# [[menu.main]]
#   name = "resume"
#   identifier = "resume"
#   weight = 300
#   url = "/resume/"

[params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'",
             "https://electricgerbil.art/",
             "https://*.electricgerbil.art/",
             "https://maxcdn.bootstrapcdn.com",
             "https://fonts.gstatic.com",
             "data:"]
  formaction = ["'self'"]
  framesrc = ["'self'",
              "youtube.com",
              "www.youtube.com"]
  imgsrc = ["'self'",
            "https://electricgerbil.art/",
            "https://*.electricgerbil.art/",
            "data:",
            "https://www.gravatar.com",
            "https://ssl.gstatic.com",
            "https://www.gstatic.com",
            "https://www.google-analytics.com"]

  objectsrc = ["'none'"]
  connectsrc = ["'self'", "https://www.google-analytics.com"]
  stylesrc = ["'self'",
              "https://electricgerbil.art/",
              "https://*.electricgerbil.art/",
              "'unsafe-inline'",
              "https://maxcdn.bootstrapcdn.com",
              "https://fonts.googleapis.com",
              "https://cdn.jsdelivr.net",
              "https://tagmanager.google.com",
              "https://fonts.googleapis.com"]
  scriptsrc = ["'self'",
		       "'unsafe-inline'",
		       "'unsafe-eval'",
           "https://electricgerbil.art/",
           "https://*.electricgerbil.art/",
		       "https://cdn.jsdelivr.net",
		       "https://oss.maxcdn.com",
		       "https://www.google-analytics.com",
		       "https://ssl.google-analytics.com",
		       "cse.google.com",
		       "https://www.google.com",
		       "https://pagead2.googlesyndication.com",
		       "https://adservice.google.com",
		       "https://www.googletagservices.com",
		       "https://tagmanager.google.com",
           "https://*.googletagmanager.com"
		       ]

